### ISSUE TITLE
Function definition in nested table not properly linked

### ISSUE THREAD

**Issue by turpid-monkey** [turpid-monkey/LuaAutoComplete#27]
The following source produces the wrong completion "problem2(a,b)":

```lua
problem = {
   foo = function(a,b) return a+b end
}
```

**Comment by miho** [comment]
still doesn't work. now the function completion is `foo(a,b)`. but should be `problem.foo(a,b)`.

**Comment by miho** [comment]
Hmm, seems to work well in many cases:

<img width="467" alt="screenshot 2015-12-11 11 43 05" src="https://cloud.githubusercontent.com/assets/225266/11741947/7c540c36-9ffc-11e5-8d4a-0b18efcef1dd.png">

**Comment by turpid-monkey** [comment]
Which, in absolute terms, means it works.

**Comment by miho** [comment]
Doesn't seem to be reproducible.
